run:
  tests: true
  timeout: 5m
linters:
  disable-all: true
  enable:
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - revive
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - copyloopvar
    - unconvert
    - whitespace
    - asciicheck
    - gocognit
    - godot
    - nestif
    - prealloc
    - testpackage
    - wsl
linters-settings:
  lll:
    line-length: 120
  funlen:
    lines: 70
    statements: 50

  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated