services:
  as-db:
    image: postgres:16.4-alpine3.20
    restart: always
    ports:
      - 23432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    networks:
      - core-as

volumes:
  postgres-data:

networks:
  core-as:
